@URL = http://localhost:3000

### get all locations
GET {{URL}}/locations

### get location by id
GET {{URL}}/locations/2

### update a location
PUT {{URL}}/locations/4
Content-Type: application/json

{
    "availableItems": 1,
    "collectedItems": 1
}

### get all products
GET {{URL}}/orders

### get if order is enabled
GET  {{URL}}/enabled

### get all products
GET {{URL}}/products

### post new order
POST {{URL}}/orders
Content-Type: application/json

[
    {"id": 0, "purchased": "false"},
    {"id": 1, "purchased": "true"},
    {"id": 2, "purchased": "true"},
    {"id": 3, "purchased": "true"}
]